```plantuml
@startuml
left to right direction

actor "Сотрудник деканата"
actor "Преподаватель"
actor "Студент"
actor "Администратор системы"
actor "Служба авторизации"
actor "Внутренняя система университета"
actor "Аналитическая система"

(ИС деканата)

"Сотрудник деканата" --> (ИС деканата)
"Преподаватель" --> (ИС деканата)
"Студент" --> (ИС деканата)
"Администратор системы" --> (ИС деканата)

(ИС деканата) --> "Служба авторизации"
(ИС деканата) --> "Внутренняя система университета"
(ИС деканата) --> "Аналитическая система"

@enduml
```