@startuml
interface Человек {
    +getФИО()
    +setФИО(фио)
}
interface Документ {
    +getНомер()
    +getДата()
    +валидировать()
}
interface Аудитируемый {
    +датаСоздания
    +датаИзменения
    +getИсторияИзменений()
}

class Студент {
    +номер_студенческого_билета
    -ФИО
    -дата_рождения
    #группа
    +getАкадемическийСтатус()
}
class Группа {
    +номер_группы
    +специальность
    +год_поступления
    +форма_обучения
    -список_студентов
}
class Факультет {
    +название
    +декан
    -список_групп
    #бюджет
}
class Преподаватель {
    +ФИО
    +дисциплины
}
class Оценка {
    +значение
    +дата
}
class Дисциплина {
    +название
    +код
}
class Приказ {
    +номер
    +дата
    +тип
    +основание
    -подпись_декана
}
class Академический_отпуск {
    +дата_начала
    +дата_окончания
    +причина
    -документы_основания
}

' Реализация интерфейсов (пунктирные стрелки)
Студент ..|> Человек
Студент ..|> Аудитируемый
Преподаватель ..|> Человек
Приказ ..|> Документ
Приказ ..|> Аудитируемый

' Связи между сущностями
Студент "1" -- "1" Группа : учится в
Группа "1..*" -- "1" Факультет : относится к
Студент "1" -- "*" Оценка : имеет
Дисциплина "1" -- "*" Оценка : по
Преподаватель "1" -- "*" Дисциплина : преподает
Студент "1" -- "*" Приказ : является объектом
Академический_отпуск --|> Приказ : является типом
Дисциплина "*" -- "*" Группа : изучается

@enduml
