@startuml

entity Студент {
    номер_студенческого_билета
    ФИО
    дата_рождения
    группа
}

entity Группа {
    номер_группы
    специальность
    год_поступления
    форма_обучения
}

entity Факультет {
    название
    декан
}

entity Дисциплина {
    название
    количество_часов
    семестр
}

entity Оценка {
    тип_аттестации: "экзамен" или "зачет"
    дата
    оценка
}

entity Преподаватель {
    ФИО
    ученая_степень
    должность
}

entity Приказ {
    номер
    дата
    тип: "академический отпуск", "перевод", "отчисление"
    основание
}

entity Академический_отпуск {
    дата_начала
    дата_окончания
    причина
}

Студент "1" -right- "1" Группа : учится в
Группа "1..*" -down- "1" Факультет : относится к

Студент "1" -right- "*" Оценка : имеет
Дисциплина "1" -left- "*" Оценка : по

Преподаватель "1" -down- "*" Дисциплина : преподает

Студент "1" -up- "*" Приказ : является объектом
Академический_отпуск "1" --|> Приказ : является типом

Дисциплина "*" -down- "*" Группа : изучается

@enduml